dist: trusty
language: java
jdk:
  - oraclejdk8
env:
 - NODE_VERSION=10
install:
  - nvm install $NODE_VERSION
  - npm install
script:
  - nvm use $NODE_VERSION
  - npm run build
  - npm run lint
  - npm run generate
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  local-dir: output
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
